spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

security:
  jwt:
    token:
      secret-key: keyf
      expire-length: 300000

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data