services:
  postgres:
    image: sameersbn/postgresql:10-2
    ports:
      - "5432:5432"
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    environment:
      - DB_USER=user
      - DB_PASS=user
      - DB_NAME=localdb